Store and check coverage

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -86,6 +86,8 @@ references:
     run:
       name: Install dependencies
       command: |
+        sudo apt-get update
+        sudo apt-get install bc
         if [ "${CIRCLE_NODE_INDEX}" == "0" ]; then
           bundle config deployment true
           bundle check || bundle install && bundle clean
@@ -128,6 +130,23 @@ references:
         bundle exec rails parallel:create
         bundle exec rails parallel:load_structure
         bundle exec rails parallel:spec
+
+  store_coverage: &store_coverage
+    store_artifacts:
+      path: coverage
+
+  check_coverage: &check_coverage
+    run:
+      name: Check test coverage
+      command: |
+        limit=95 # Coverage percentage below this number will cause the build to fail
+        coverage=$(grep -o '"line":.*' coverage/.last_run.json | cut -d" " -f2-)
+        echo "Details of test coverage is available from the Artifacts tab"
+        echo "Tests cover $coverage% of code"
+        if (( $(echo "$coverage < $limit" | bc -l) )); then
+          echo "This is under the target of $limit%"
+          exit 1
+        fi
 
   aws_setup: &aws_setup
     # Authenticate to AWS using OIDC v2 with the AWS CLI
@@ -222,6 +241,8 @@ jobs:
       - *brakeman
       - *update_chrome
       - *run_unit_and_feature_tests
+      - *store_coverage
+      - *check_coverage
 
   build_branch_and_push_to_ecr:
     executor: machine_executor
